### ISSUE TITLE
DatePicker öffnet nicht beim Click auf die Icons

### ISSUE THREAD

**Issue by dtomasi** [kmielke/calendar_extended#22]
System: Contao 3.4.4

**Comment by kmielke** [comment]
Kann ich mit Contao 3.4.4/3.4.5 und der aktuellen calendar_extended nicht reproduzieren.
Im Zweifel ist es leider auch kein Bug meiner Erweiterung, sondern ein Bug von MultiColumnWizard. Siehe dazu Issues https://github.com/kmielke/calendar_extended/issues/20.

**Comment by dtomasi** [comment]
Danke für die Info. Werde dem mal nachgehen.
