### ISSUE TITLE
Kalendar Picker wird nicht angezeigt

### ISSUE THREAD

**Issue by akroii** [kmielke/calendar_extended#23]
Wenn ich bei einem Event im Teaser den Kalender Picker verwende (z.b. bei unregelmäßige Wiederholungen) erscheint dieser ohne Styles ausserhalb der Seite.
Fehler tritt beim smart_backend_theme und bei default theme (von Contao) auf.

![err](https://cloud.githubusercontent.com/assets/8830861/7488038/fc61291c-f3c3-11e4-8402-963f0a2db132.jpg)

**Comment by kmielke** [comment]
Hallo erst mal,

wie wäre es mit einigen Versions-Info's?
Also, welche Contao Version?
welche Version der Erweiterung, und welche Version der Erweiterung MulticolumnWizard.

Gruß Kester

**Comment by kmielke** [comment]
Siehe https://github.com/menatwork/MultiColumnWizard/issues/173
Sobald die aktuelle Version da funktioniert, werde ich meine Erweiterung dafür freigeben.

Dann sollte das klappen.
Gruß Kester

**Comment by akroii** [comment]
Contao 3.4.4
calendar_extended 3.2.0 Build 120
MultiColumnWizard	3.2.3 Build 3
