### ISSUE TITLE
full_event Umsetzung nicht kompatibel!

### ISSUE THREAD

**Issue by SpeGal** [kmielke/calendar_extended#25]
Das folgende Problem wurde im Core geändert, die Erweiterung calendar_extended scheint dieses Update aber aufzuheben:
https://github.com/contao/core/issues/8081

Nur wenn ich die Erweiterung in den Einstellungen ignoriere, funktioniert der Kalender wieder einwandfrei. Mit Erweiterung bleibt das Problem wie vor dem Update bestehen ...

**Comment by kmielke** [comment]
Fehler ist behoben.
