### ISSUE TITLE
timeFormat wird ignoriert im Stundenplan

### ISSUE THREAD

**Issue by Metis77** [kmielke/calendar_extended#27]
$event['time'] gibt nicht das 24h Format aus, auch wenn in den Einstellungen von Contao "H:i" steht.

**Comment by kmielke** [comment]
Hi,
kann ich so nicht reproduzieren. Ich habe sowohl in den Globalen-Einstellungen, als auch in den Seitenstruktur-Einstellungen "H:i" als Zeitformat, und im Stundenplan bekomme ich dann z.B. "18:00 - 19:00" im Event angezeigt. Am Template cal_timetable.html5 habe ich nichts geändert.

Gibt es noch mehr Hinweise?
Gruß Kester

**Comment by Metis77** [comment]
ah ok, in der Seitenstruktur war das Format noch falsch gestanden.
Vielen Dank für den Tipp!
