### ISSUE TITLE
Verbesserung: Erweitere EFG-Anzeige

### ISSUE THREAD

**Issue by rolandschuetz** [kmielke/calendar_extended#30]
Wenn man für mehrere Events das selbe Formular verwendet wird es leider ziemlich unübersichtlich.

Es wäre daher fein, wenn man in der EFG-Datenansicht das Event mit Name anzeigt.

**Comment by kmielke** [comment]
Kommt in der nächsten Version. Dafür muss ebenfalls ein verstecktes Feld "eventtitle" im Formular angelegt werden, also wie beim Feld "eventid".
