### ISSUE TITLE
BUG: Datumsberechnung

### ISSUE THREAD

**Issue by rolandschuetz** [kmielke/calendar_extended#31]
Contao 3.5.4
calendar_extended 3.5.0 Build 36

Ich habe folgende Event-Werte:
Startzeit: 17.02.2016
Endzeit: leer
Zeit hinzufügen: angehakerlt
Starrtzeit: 04:00
Endzeit: 13:59
Keine wiederkehrenden Events, weder vom Core noch von der Erweiterung

Der ModuleEventReader berechnet nun folgenden Wert für date: 17.02.2016
Erwartet wäre: 17.02.2016 04:00 - 13:59

Bei mehrtätigen Events wird die Zeit zum $this->date hinzugefügt, warum bei eintätigen nicht?

Danke,
Roland

**Comment by kmielke** [comment]
wenn du kein Feature der Erweiterung nutzt, was passiert denn, wenn du die mal in den Einstellungen deaktivierst?

**Comment by kmielke** [comment]
Habe das mal mit der 3.5.6 verglichen. Da gibt es Contao Fixes im Bereich Kalender. In der 3.5.6 geht es nämlich. Mein Test sieht so aus.
**17.02.2016, 04:00 – 13:59 Tai Chi Einführung**

Also kein Bug meiner Erweiterung.

**Comment by rolandschuetz** [comment]
Kann ich bestätigen. Passt alles.
