### ISSUE TITLE
Datumsformat-Fehler

### ISSUE THREAD

**Issue by rolandschuetz** [kmielke/calendar_extended#33]
Contao 3.5.12
calendar_extended 3.6.0 Build 23

Ich verwende keine wiederkehrenden Events, weder vom Core noch von der Erweiterung

Fall 1:
Endzeit ignorieren: angehackerlt
Zeit hinzufügen: angehakerlt
Startdatum: 29.05.2016
Enddatum: 31.05.2016
Endzeit: leer
Starrtzeit: 04:00
Der ModuleEventReader berechnet nun folgenden Wert für date: 29.05.2016
Erwartet wäre: 29.05.2016 04:00 – 31.05.2016

Fall 2:
Zeit hinzufügen: nicht angehakerlt
Startdatum: 29.05.2016
Enddatum: 31.05.2016
Der ModuleEventReader berechnet nun folgenden Wert für date: 29.05.2016
Erwartet wäre: 29.05.2016 – 31.05.2016

Fall 3:
Endzeit ignorieren: nicht angehackerlt
Zeit hinzufügen: angehakerlt
Startdatum: 29.05.2016
Enddatum: 31.05.2016
Starrtzeit: 04:00
Endzeit: 06:00
Ergebnis wie erwartet, nur zur Veranschaulichung der Unregelmässigkeit: 29.05.2016 04:00 – 31.05.2016 06:00

Warum gibt es überhaupt dieses "Endzeit ignorieren", warum die Beschreibung von "Endzeit" auch sagt einfach den gleichen Wert wie beim Startdatum setzen?

Danke,
Roland

**Comment by rolandschuetz** [comment]
Ich würde ein Ergebnis dieser Art erwarten:
    $timeFormat = 'H:i';
    $dateFormat = ($GLOBALS['TL_LANGUAGE'] == 'en') ? 'd/m/Y' : 'd.m.Y';
    $dateTimeFormat = ($GLOBALS['TL_LANGUAGE'] == 'en') ? 'd/m/Y H:i' : 'd.m.Y H:i';

    $date = '';
    if(!$this->addTime) {
      $date = date($dateFormat, $this->startDate);
      if(!empty($this->endDate) && $this->startDate != $this->endDate) {
        $date .= ' - ' . date($dateFormat, $this->endDate);
      }
    } else {
      $date = date($dateTimeFormat, $this->startTime);
      if($this->ignoreEndTime) {
        // just the the end date, it multi-date event
        if(!empty($this->endDate) && $this->startDate != $this->endDate) {
          $date .= ' - ' . date($dateFormat, $this->endDate); // multi-day event with end time
        }
      } else if(!empty($this->endDate) && $this->startDate != $this->endDate) {
        $date .= ' - ' . date($dateTimeFormat, $this->endTime); // multi-day event with end time
      } else if(!empty($this->endTime)) {
        $date .= ' - ' . date($timeFormat, $this->endTime); // single day with end time
      }
    }

**Comment by kmielke** [comment]
Ich habe einen kleinen Fix gemacht bzgl. "Endzeit ignorieren", der sich auf die Darstellung bezieht. Der Rest ist mit der aktuellen Contao Version nicht reproduzierbar.
