### ISSUE TITLE
Im TPL event_full wird nur die Formid angezeigt

### ISSUE THREAD

**Issue by lkrempler** [kmielke/calendar_extended#34]
Leider wird bei mir im event_full Template nur die Formid angezeigt, aber das Formular selbst nicht gerendert. 
Gibts schon Erfahrungen warum dies so ist, kann dazu in den Suchmaschinen nichts finden.

**Comment by kmielke** [comment]
Mit welchem Modul benutzt du das Template? Das Formular wird nur über den EventReader gerendert, nicht in einer Liste...

**Comment by lkrempler** [comment]
Modul ist der Eventleser mit dem Standart Template.

**Comment by kmielke** [comment]
Bitte schau noch mal genau in die Doku und im Forum nach. Mit der aktuellen Beschreibung kann ich leider nichts anfangen, weil ich es nicht reproduzieren kann.
