### ISSUE TITLE
Laufende Events werden in up_coming nicht angezeigt.

### ISSUE THREAD

**Issue by chriza** [kmielke/calendar_extended#35]
Hi,
in einem List-Modul zur Anzeige aller Events der nächsten zwei Wochen, werden (in der Vergangenheit begonnenden und noch) laufende Events nicht angezeigt.

Für das Core-Modul ModuleEventList ist ab der Version 3.5.18 dieser Fehler behoben worden.
In 3.5.21 lautet die entsprechende Stelle im Modul:
// Skip occurrences in the past but show running events (see #8497)
if ($event['repeatEnd'] && $event['end'] < $intStart)
{
  continue;
}
Ist es möglich, diese Funktionalität hier auch einzubauen?

**Comment by kmielke** [comment]
Glaube, es ist hier im GIT schon drin, kommt aber auf jeden Fall ins nächste Release.

**Comment by chriza** [comment]
Ich habe die Version installiert.
Funktioniert:  ja und nein.
Nein bei der verkürzten Darstellung.

![grafik](https://cloud.githubusercontent.com/assets/1572887/21744832/03eed0d4-d51e-11e6-89a5-d0b6e3cf5592.png)
