### ISSUE TITLE
PHP 7: function name must be a string

### ISSUE THREAD

**Issue by reluem** [kmielke/calendar_extended#36]
Hi,
when switching to PHP 7, your module throws exceptions.
I already tried the latest dev version (3.5.x-dev (e8dbbc90)), but that did not change a thing

>  PHP Fatal error: Uncaught exception 'Error' with message 'Function name must be a string' thrown in /is/htdocs/xx/www/xx/composer/vendor/kmielke/calendar_extended/classes/EventsExt.php on line 533

Any ideas how to fix this?

Thanks!

Contao 3.5.24

**Comment by Znrl** [comment]
`$this->arrEvents = $this->$callback[0]->$callback[1]($this->arrEvents, $arrCalendars, $intStart, $intEnd, $this);`
in line 533 add { } like this, could already be enough
`$this->arrEvents = $this->$callback[0]->{$callback[1]}($this->arrEvents, $arrCalendars, $intStart, $intEnd, $this);`

**Comment by reluem** [comment]
unfortunately this did not work:

> [24-Jan-2017 22:04:40 Europe/Berlin] PHP Fatal error: Uncaught exception 'Error' with message 'Call to a member function getAllEvents() on null' thrown in /is/htdocs/xxx/www/xxx/composer/vendor/kmielke/calendar_extended/classes/EventsExt.php on line 533
> #0 composer/vendor/kmielke/calendar_extended/modules/ModuleEventlist.php(207): Contao\EventsExt->getAllEventsExt(Array, 1485291880, 2145913200, Array)
> #1 system/modules/core/modules/Module.php(287): Contao\ModuleEventlist->compile()
> #2 composer/vendor/kmielke/calendar_extended/modules/ModuleEventlist.php(112): Contao\Module->generate()
> #3 system/modules/core/elements/ContentModule.php(59): Contao\ModuleEventlist->generate()
> #4 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
> #5 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Contao\ContentModel, 'main')
> #6 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
> #7 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #8 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
> #9 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Contao\ArticleModel, false, false, 'main')
> #10 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
> #11 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Contao\PageModel, true)
> #12 index.php(20): Contao\FrontendIndex->run()


Thanks for your help on this!

**Comment by Znrl** [comment]
Does it work like this?
`$this->arrEvents = $this->{$callback[0]}->{$callback[1]}($this->arrEvents, $arrCalendars, $intStart, $intEnd, $this);`

**Comment by reluem** [comment]
seems to be working! 
Awesome 👍

**Comment by kmielke** [comment]
Fixed...
