### ISSUE TITLE
IgnoreEndTime führt zu diversen Fehlern

### ISSUE THREAD

**Issue by wiphi** [kmielke/calendar_extended#38]
Contao 3.5.24
Betrifft calendar_extended Version 3.7.2 und vorherige

Das Feld "Endzeit ignorieren" führt bei mir zu diversen Fehlern. Ich konnte dabei zwei problematische Stellen im Source finden:
dca\tl_calendar_events.php, Zeile 605 ff.
```php
        // Set endtime to starttime always...
        if ($dc->activeRecord->ignoreEndTime) {
            //$arrSet['endTime'] = strtotime(date('d.m.Y', $arrSet['endTime']) . ' 23:59:59');
            $arrSet['endTime'] = $arrSet['startTime'];
        } // Adjust end time of "all day" events
        elseif ((strlen($dc->activeRecord->endDate) && $arrSet['endDate'] == $arrSet['endTime']) || $arrSet['startTime'] == $arrSet['endTime']) {
            $arrSet['endTime'] = (strtotime('+ 1 day', $arrSet['endTime']) - 1);
        }
```
Hier wird die Endzeit auf 23.59 Uhr gesetzt (auskommentiert) und gespeichert. In der Frontendausgabe wird dann immer bis 23.59 Uhr ausgegeben.

Da ist auch schon das zweite Problem in modules\ModuleEventlist.php, Zeile 325 ff.
```php
                    // Set endtime to starttime always...
                    if ((int)$event['ignoreEndTime'] === 1) {
                        $event['date'] = \Date::parse($objPage->datimFormat, $event['startTime']) . ' - ' .   \Date::parse($objPage->dateFormat, $event['endTime']);
                        $event['endTime'] = '';
                        $event['time'] = '';
//                        if ($event['addTime']) {
//                            $event['time'] = \Date::parse($objPage->timeFormat, $event['startTime']);
//                        }
                    }
```
Das `$event['time'] = '';` verhindert die Ausgabe der Startzeit. Kommentiere ich die Zeile aus, wird die Startzeit wieder korrekt ohne Endzeit ausgeben.

Mache ich etwas falsch oder ist das ein Bug? Gerne erstelle ich hierfür auch einen PR.

**Comment by kmielke** [comment]
Schau ich mir an...

**Comment by kmielke** [comment]
So, aus meiner Sicht mit dem aktuellen Release erledigt.

**Comment by wiphi** [comment]
Sieht gut aus, Danke!
