### ISSUE TITLE
Falsches Template in ModuleEventReader

### ISSUE THREAD

**Issue by JoTrautner** [kmielke/calendar_extended#40]
Unter Contao 4.3 wird bei Aufruf der Seite mit dem Eventleser im FE ein Fehler produziert, im Logfile findet sich  > Could not find template \"mod_event\" <

In der Klasse ModuleEventReader steht
protected $strTemplate = 'mod_event';

Müsste m.M. nach  
protected $strTemplate = 'mod_eventreader';
heißen. Ersetzt man das entsprechend, funktioniert's.

**Comment by kmielke** [comment]
Datei calendar_extended/templates/mod_event.html5 hinzugefügt. Ist dann im nächsten Release drin.
