### ISSUE TITLE
Calendar-Frontendmodul ignoriert Ferien-Einstellungen

### ISSUE THREAD

**Issue by srhinow** [kmielke/calendar_extended#41]
Ich verwende  calendar_extended V 3.6.0 aus dem Contao ER und Contao 3.5.27.

Website: https://www.pritzwalk-taekwondo.de/tkd-termine.html?month=201706

Die Events 13.06 - 23.06 dürften in dem linken Kalender nicht angezeigt werden.

Ich habe einen Kalender als Ferien-Kalender eingerichtet. In der Eventliste funktioniert es auch wie es soll, das die Trainings in der Ferienzeit nicht angezeigt werden. Nur in dem Kalender links werden die Ferien trotzdem als Link angezeigt. Alle Einstellungen sind in dem Eventlist-Modul und dem Calendar (small) die selben und greifen auf die selben Calendar zu und haben den gleichen Ferienkalender.

Ich habe außerdem dca/modules.php der palette "calendar" das Feld "show_holiday" hinzugefügt, da sonst alle Feirentage verlinkt werden und ich keine Möglichkeit habe dies abzustellen.

**Comment by kmielke** [comment]
Die Version aus dem ER wird schon länger nicht mehr gepflegt. Nur noch die aus dem Composer, oder aus dem Git. Bitte auf diese Version (aktuell https://github.com/kmielke/calendar_extended/releases/tag/3.7.5) wechseln.
