### ISSUE TITLE
#41 ist auch mit  der aktuellen 3.7.5 noch aktuell

### ISSUE THREAD

**Issue by srhinow** [kmielke/calendar_extended#42]
ich habe eben die Version 3.7.5 hier von github gezogen, das alte Modul gelöscht und das neue online gestellt, die DB aktualisiert. Das in #41 beschriebene Problem besteht weiterhin.

**Comment by kmielke** [comment]
Bitte mal die Einstellungen der Events und des Modules posten.

**Comment by kmielke** [comment]
Bei mir funktioniert das. Zur Info: alle Module bekommen ihre Events aus ein und der selben Funktion aus der Klasse EventsExt.php.

**Comment by kmielke** [comment]
ah... verstehe. Es werden nur die Links angezeigt, obwohl keine Events da sind. Ok, schaue ich mir mal an.

**Comment by srhinow** [comment]
ich hab dir über das Forum eine Nachricht zukommen lassen. Damit du dir das gerne im BE ansehen kannst.

**Comment by srhinow** [comment]
![einstellungen_calendar_training](https://cloud.githubusercontent.com/assets/741418/26353698/e8017e8a-3fc1-11e7-8197-f7df99c5c8ec.png)
![einstellungen_ferienkalender](https://cloud.githubusercontent.com/assets/741418/26353697/e7fe77bc-3fc1-11e7-8844-4319845f82b7.png)
![modul_einstellungen_calendar_small](https://cloud.githubusercontent.com/assets/741418/26353699/e805a794-3fc1-11e7-9453-32e1ebf39da6.png)
![modul_einstellungen_eventliste](https://cloud.githubusercontent.com/assets/741418/26353700/e80fcc4c-3fc1-11e7-9bba-db08d5adfc94.png)



](url)

**Comment by srhinow** [comment]
da ich ja die dca/modules.php in der Palette calendar um das Feld show_holiday in der alten Version beschrieben habe werden auch nicht alle Tage von den Ferien im kleinen Kalender angezeigt sondern "nur" noch die Trainingstage.

`// Palette for calendar
$GLOBALS['TL_DCA']['tl_module']['palettes']['calendar'] = str_replace
(
    ';{redirect_legend}',
    ';{config_ext_legend},cal_holiday,show_holiday,ignore_urlparameter;{redirect_legend}',
    $GLOBALS['TL_DCA']['tl_module']['palettes']['calendar']
);`

**Comment by kmielke** [comment]
Hallo Sven, im neuen Release sollte jetzt passen. Habe show_holiday übernommen.

Gruß Kester

**Comment by srhinow** [comment]
Hallo Kester,
super es funktioniert jetzt wie es soll -> Danke.
Hab per Paypal dafür auch ne kleine Spende hinterlassen.

Gruß Sven

**Comment by kmielke** [comment]
Vielen Dank. 👍
Da freue ich mich.
