### ISSUE TITLE
Modul Registrierung

### ISSUE THREAD

**Issue by chriza** [kmielke/calendar_extended#43]
Nach Installation dieses Modules fehlt im Registrierungsformular die Legende "Editierbare Felder" für die Abfrage der Memberdaten.

**Comment by kmielke** [comment]
geht es etwas genauer?

**Comment by chriza** [comment]
Habe mich falsch ausgedrückt. In der Legende "Modul-Konfiguration" fehlen die "Editierbaren Felder" mit den Member-Feldern
[vor-der-installation.pdf](https://github.com/kmielke/calendar_extended/files/1095273/vor-der-installation.pdf)
[nach-der-installation.pdf](https://github.com/kmielke/calendar_extended/files/1095274/nach-der-installation.pdf)

**Comment by kmielke** [comment]
und was ist diese Registrierung?

**Comment by chriza** [comment]
Die Registrierung für die Website. Sie hat mit dem Kalender eigentlich nichts zu tun. Wird aber nach der Installation der Extension verändert.

**Comment by kmielke** [comment]
und was ist das? eine andere Erweiterung?

**Comment by kmielke** [comment]
ok. hab's gesehen und gefixt. Release 3.7.7 ist raus.
Danke...
