### ISSUE TITLE
Fehlermeldung bei einem unveröffentlichten Event

### ISSUE THREAD

**Issue by joke1** [kmielke/calendar_extended#44]
Unter 4.4 gibt es im Frontend eine unschöne Fehlermeldung & das Layout ist zerschossen, wenn ein Event nicht veröffentlicht ist, man sich im Eventreader befindet & in der Seitenstruktur eine 404 Seite definiert wurde:

`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getRelated() on null at .../vendor/kmielke/calendar_extended/modules/ModuleEventReader.php:107)"} []
`

Scheinbar gibt es ein Problem mit der Generierung der eigenen 404 Seite, welche ja eigentlich den Code ab Zeile 107 nicht mehr ausführen sollte. 
Wenn man die eigene 404 Seite unsichtbar schaltet, funktioniert es wieder.
Wenn man alles weitere ab Zeile 107 nur ausführt, wenn $objEvent nicht null ist, ist die Fehlermeldung oben zwar weg, das Frontend ist aber weiterhin zerschossen.

Andere 404 Seiten außerhalb des Eventreaders funktionieren.

**Comment by kmielke** [comment]
Wird für diese Version für Contao 3.5.x nicht mehr gemacht.
