### ISSUE TITLE
Problem in dca/tl_calendar.php

### ISSUE THREAD

**Issue by arno1979** [kmielke/calendar_extended#45]
Hallo Kester,
meiner Meinung nach verhindert eine kleine Abweichung vom Contao-Standard in der Datei dca/tl_calendar.php das korrekte verstecken des Feldes `allowEvents` in der Palette beim Neuanlegen eines Kalenders.

Aktuell lautet die Konfiguration für das Feld `isHolidayCal`
```php
$GLOBALS['TL_DCA']['tl_calendar']['fields']['isHolidayCal'] = array
(
    'label' => &$GLOBALS['TL_LANG']['tl_calendar']['isHolidayCal'],
    'default' => 0,
    'exclude' => true,
    'inputType' => 'checkbox',
    'eval' => array('submitOnChange' => true, 'tl_class' => 'w50'),
    'sql' => "char(1) NOT NULL default '0'"
);
```

Formuliert man das so
```php
$GLOBALS['TL_DCA']['tl_calendar']['fields']['isHolidayCal'] = array
(
    'label' => &$GLOBALS['TL_LANG']['tl_calendar']['isHolidayCal'],
    'exclude' => true,
    'inputType' => 'checkbox',
    'eval' => array('submitOnChange' => true, 'tl_class' => 'w50'),
    'sql' => "char(1) NOT NULL default ''"
);
```

blendet Contao beim Aktivieren bzw. Deaktivieren der Checkbox `isHolidayCal` das Feld `allowEvents` korrekt ein und aus.
Nach einem schnellen grep auf deinen Code sieht es für mich nicht danach aus, dass es einen Unterschied macht, ob in der Datenbank 0 oder leer gespeichert wird.
Eine entsprechende Änderung im DCA sollte also keine weiteren Änderungen nach sich ziehen.

Viele Grüße
Arno

**Comment by kmielke** [comment]
Hallo Arno,

ist eingecheckt. Danke
Grüße Kester
