### ISSUE TITLE
Berücksichtigung von Wiederholungsterminen

### ISSUE THREAD

**Issue by arno1979** [kmielke/calendar_extended#46]
Hallo Kester,

danke für https://github.com/kmielke/calendar_extended/commit/fc406bd89ed5938e93fd246ba1fc7efc746d7c39.

Jetzt ist uns noch etwas gravierenderes aufgefallen und ich wollte das gerne mit dir abgleichen.

Und zwar erscheint es uns, als ob bei Ausnahmeterminen die als Wiederholungstermine konfiguriert sind, nur der ursprüngliche Termin berücksichtigt wird, nicht aber die berechneten Wiederholungen.

Kurzes Beispiel:
- im Ferienkalender ist ein Termin angelegt "Montags geschlossen"
- Beginn ist der 02.01.2017 (also der erste Montag des Jahres)
- Unter "Wiederholungen" ist als Intervall "1 Woche(n)" und Wiederholungen "0" (= unendlich bzw. bis 2038) eingestellt
- im normalen Veranstaltungskalender ist ein Ausstellungstermin als mehrtägiges Event vom 01.09.2017 bis 22.11.2017 angelegt
- ich würde erwarten, dass in einer entsprechend konfigurierten Liste (mit ausführlicher Ansicht, sprich nicht "verkürzt") bzw. einem Mini-Kalender die Montage dann nicht angezeigt bzw. verlinkt würden – die Events tauchen aber trotzdem auf

Wir haben uns darauf hin deine Klasse EventsExt.php genauer angesehen und den entsprechenden Abschnitt gefunden. Ab Zeile 480 werden die Events aus dem Ferienkalender durchlaufen und es gibt eine Behandlung für mehrtägige Events (getrennt in das Ausgangsevent ab Zeile 492 und die Events an den folgenden Tagen ab Zeile 516).
Die in regel- oder unregelmäßigen Wiederholungstermine werden davon aber nicht abgedeckt. In deinen Schleifen werden immer nur Zeitspannen berücksichtigt, aber keine einzelnen Ausnahmen mit zeitlichen Lücken dazwischen. Jedenfalls wenn ich den Code richtig lese.

Ich habe sogar ein entsprechendes Feld `repeatDates` in den Ausnahemevents gefunden, in dem die Wiederholungstermine komplett als serialisierter Array gespeichert sind. Abgefragt und ausgewertet wird dieses Feld allerdings nirgends in EventsExt.php.

Kannst du diese Beobachtungen bestätigen?

Viele Grüße
Arno

**Comment by kmielke** [comment]
Hallo Arno, ja, das ist richtig. Wiederholungen werden bei den Ferienkalendern aktuell nicht berücksichtig. 
Gruß Kester

**Comment by arno1979** [comment]
Ok, dann bin ich ja immerhin froh, dass ich den Code richtig gelesen habe. :)

Könntest du dir denn vorstellen dieses Feature noch mit aufzunehmen?
Die Konfigurationsmöglichkeiten im Backend legen ja nahe, dass diese Art von Ausnahmeevents verwendet werden kann.

Ich habe die Funktion für uns selber gebaut und in einer Override Klasse für die EventsExt.php ab Zeile 542 eingebaut:
```php
// unset all days of a recurring event
if ($objEvents->repeatDates)
{
    $exceptionRepeatDatesArr = array_keys(deserialize($objEvents->repeatDates));
}
$recurringExceptions = array();

if ($recurringExceptionsArr)
{
    // build array with recurring exception dates from repeatDates field of current holiday to get relevant timespan
    foreach ($exceptionRepeatDatesArr as $key => $exceptionTimestamp)
    {
        $date = date('Ymd', $exceptionTimestamp);
        if (array_key_exists($date,$this->arrEvents))
        {
            $recurringExceptionsArr[] = date('Ymd', $exceptionTimestamp);
        }
    }

    foreach ($recurringExceptionsArr as $exceptionTimestamp => $exceptionDate)
    {
        if ($this->arrEvents[$exceptionDate])
        {
            foreach ($this->arrEvents[$exceptionDate] as $k1 => $events) {
                foreach ($events as $k2 => $event) {
                    // do not remove events from any holiday calendar
                    $isHolidayEvent = array_search($event['pid'], $arrHolidays);

                    // unset the event if showOnFreeDay is not set
                    if ($allowEvents === false) {
                        if ($isHolidayEvent === false) {
                            unset($this->arrEvents[$exceptionDate][$k1][$k2]);
                        }
                    } else {
                        if ($isHolidayEvent === false && !$event['showOnFreeDay'] == 1) {
                            unset($this->arrEvents[$exceptionDate][$k1][$k2]);
                        }
                    }
                }
            }
        }
    }
}
```
Kannst du ja mal überlegen, ob das aus deiner Sicht Sinn macht.

Ich bin noch nicht 100% glücklich mit der Art wie am Anfang der Array `$recurringExceptionsArr` gebaut wird, um zu ermitteln welche Zeitspanne abgedeckt werden soll.
Ich mache das, weil wir z. B. mit Ausnahmeevents arbeiten wollen, die für einen unendlich langen Zeitraum immer Montags den Schließtag einer Einrichtung abbilden sollen.
Damit dann aber nicht jedesmal in der Foreach-Schleife alle Montage bis 1.1.2038 durchlaufen werden müssen, baue ich halt den Array `$recurringExceptionsArr`, der vorher mit `$this->arrEvents` den relevanten Zeitraum abgleicht.

Viele Grüße
Arno
