### ISSUE TITLE
Problem Feld "allRecurrences" in dca/tl_calendar_events.php

### ISSUE THREAD

**Issue by arno1979** [kmielke/calendar_extended#47]
Hallo Kester,

wie du merkst beschäftige ich mich gerade intensiv mit deiner Erweiterung. :)

Gerade habe ich beim Speichern eines Wiederholungsevents mit folgenden Parametern auf einem unserer Testserver eine MySQL-Fehlermeldung erhalten:
- Event beginnt am 02.01.2017
- Wiederholung: Intervall 1 Wochen(n), endlos wiederholen

Fehlermeldung:
```php
Fatal error: Uncaught exception Exception with message Query error: Data too long for column 'allRecurrences' at row 1 (UPDATE tl_calendar_events SET weekday=1, startTime='1483311600', endTime=1483397999, repeatEnd=2145913200, repeatDates='a:1096:{i:1483311600;s:16:\"02.01.2017 00:00\";i:1483916400;s:16:\"09.01.2017 00:00\";i:1484521200;s:16:\"16.01.2017 00:00\";i:1485126000;s:16:\"23.01.2017 00:00\";i:1485730800;s:16:\"30.01.2017 00:00\";i:1486335600;s:16:\"06.02.2017 00:00\";i:1486940400;s:16:\"13.02.2017 00:00\";i:1487545200;s:16:\"20.02.2017 00:00\";i:1488150000;s:16:\"27.02.2017 00:00\";i:1488754800;s:16:\"06.03.2017 00:00\";i:1489359600;s:16:\"13.03.2017 00:00\";i:1489964400;s:16:\"20.03.2017 00:00\";i:1490565600;s:16:\"27.03.2017 00:00\";i:1491170400;s:16:\"03.04.2017 00:00\";i:1491775200;s:16:\"10.04.2017 00:00\";i:1492380000;s:16:\"17.04.2017 00:00\";i:1492984800;s:16:\"24.04.2017 00:00\";i:1493589600;s:16:\"01.05.2017 ...
```
Ich habe die Ausgabe nur gekürzt eingefügt, die geht noch sehr lange so weiter.

Ich war irritiert, weil ich das – wie oben geschrieben – nur auf einem unserer Server als Fehler beobachten konnte.
Ein Blick in das entsprechende Datenbankfeld zeigt aber, dass auch auf den Servern ohne Fehlermeldung der Inhalt des Feldes nur bis zum Limit des BLOB Feldes geschrieben wird und dann einfach abgeschnitten wird.
Ich konnte Abhilfe schaffen, indem ich das Feld einfach als `mediumblob` umdefiniert habe.

In dem Zuge wollte ich auch mal testen was eigentlich das Maximum an Zeichen wäre, das in diesem Feld untergebracht werden muss.
Also habe ich die Wiederholungen mal auf täglich und unendlich gestellt. Das Berechnungsfeld zeigt mir als Ende auch das erwartete Datum vom 01.01.2038 an. 
Wenn ich dann allerdings in die Datenbank schaue sehe ich, dass in das Feld `allReccurences` nur Daten bis zum 01.01.2018 geschrieben wurden.

Ist das eventuell ein Bug? Ich habe in diesem Fall die Mechanismen nicht bis zum Ende nachvollzogen, habe also keine konkreten Ideen, ob das wirklich ein Problem darstellt, weil mir auch gar nicht klar ist wo das Feld `allRecurrences` wirklich zum Einsatz kommt.

Lieben Dank
Arno

**Comment by kmielke** [comment]
Hallo Arno,
in der config gibt es einen Wert der das ganze begrenzt.
$GLOBALS['TL_CONFIG']['tl_calendar_events']['maxRepeatExceptions'] = 365;

Allerdings greift es wohl nicht in allen Konstellationen. Das schaue ich mir an.

Gruß Kester

**Comment by kmielke** [comment]
ich glaube, den hier hatte ich gefixt... ;)
