### ISSUE TITLE
Fehler bei mehrtägigen Terminen und Wiederholungen

### ISSUE THREAD

**Issue by felixpfeiffer** [kmielke/calendar_extended#48]
Hallo,
wenn ich einen Termin definiere z.B. 01.08. - 02.08. und dann Wiederholung jeden ersten Montag im Monat auswähle, wird in den Wiederholungen der Termin auf einen Tag gekürzt. Also nur noch 04.09., 02.10. etc. Das Enddatum müsste ja aber pro Wiederholung auf den 05.09. bzw. 03.10. gesetzt werden.

Ist dies bekannt?

Ich habe in der EventsExt.php ab Zeile 235 mal folgende Änderung eingefügt:

`// extended version.
$intyear = (int)date('Y', $objEvents->startTime);
$intmonth = (int)date('n', $objEvents->startTime) + 1;

$year = ($intmonth == 13) ? ($intyear + 1) : $intyear;
$month = ($intmonth == 13) ? 1 : $intmonth;

$strtotime = $arg . ' ' . $unit . ' of ' . $arrMonth[$month] . ' ' . $year;
$startTime = strtotime($strtotime . ' ' . $eventStartTime, $objEvents->startTime);
$endTime = strtotime($strtotime . ' ' . $eventEndTime, $objEvents->endTime);

if($orgDateSpan)
{
$strtotime = '+'.$orgDateSpan.' days';
$endTime = strtotime($strtotime . ' ' . $eventEndTime, $startTime);
}`

Damit scheinen die Wiederholungen korrekt bestimmt zu werden.

**Comment by kmielke** [comment]
Hi,

ein Termin kann immer nur ein definiertes Ende haben. Entweder wird es explizit gesetzt, oder es wird durch Wiederholungen errechnet. Beides zusammen ist weder von Contao, noch von meiner Erweiterung vorgesehen. Das ist also kein Fehler. Ich werde das mal einbauen, dass man keine Wiederholungen setzen kann, wenn man ein Enddatum angegeben hat.

Gruß Kester

**Comment by felixpfeiffer** [comment]
Hallo Kester,

Sorry, wenn ich das noch mal öffne ;-)

Wenn ich ein Enddatum angebe, hat das Event ja ein definiertes Ende. Nämlich am zweiten Tag.
Nur wird das bisher in den erweiterten Wiederholungen nicht beachtet.

Und, Wiederholungen bei mehrtägigen Events zu "verbieten" ist ja auch eher ein Einschränkung, die nicht sinnvoll ist. Mit meiner Anpassung, die ich dir oben geschickt habe, funktioniert es ja, weil eben die Zeitspanne ggf. mit beachtet wird.

Gruß,
Felix

**Comment by kmielke** [comment]
Hallo Felix, wie ich schon gesagt habe, ist es auch bei Contao nicht vorgesehen, dass sich mehrtägige Events wiederholen können. Und das wird es auch in meiner Erweiterung nicht geben. Wenn dein Code für dich funktioniert, dann mache daraus eine kleine Erweiterung, die meine erweitert. Ich werde es definitiv nicht einbauen.

Sorry, wenn ich den wieder zu mache...

Gruß Kester

**Comment by felixpfeiffer** [comment]
Ok, dann akzeptiere ich das so ;-)

Ungeachtet dessen, tolle Erweiterung!
