### ISSUE TITLE
Fehlende Prüfung des "count" vor Anmeldung

### ISSUE THREAD

**Issue by SpeGal** [kmielke/calendar_extended#49]
In der Dokumentation steht, dass man das Feld "count" auch für die Anmeldung mehrerer Personen nutzen kann, indem man daraus ein Textfeld macht. Das funtkioniert auch soweit. Nur wird leider vor dem Abschicken des Formulars nicht überprüft, ob die gewünschte Teilnehmerzahl überhaupt noch verfügbar ist.

Beispiel:
Max. Teilnehmer: 25
Bisher angemeldet: 5
Neue Anmeldung in Feld "count" eingegeben: 21
-> Dann sind insgesamt 26 Teilnehmer auf dem Event angemeldet obwohl es nicht so viel Plätze gibt.

Man müsste also das Feld "count" erst gegenprüfen, ob noch genügend Plätze frei sind.

Könnte das noch kurzfristig implementiert werden?

**Comment by kmielke** [comment]
Hallo David, kommt drauf an, was du unter kurzfristig verstehst. Vor Mitte/Ende November werde ich da sicherlich nicht zu kommen.
Gruß Kester

**Comment by kmielke** [comment]
Fix ist der nächsten Version enthalten. Wichtig ist, dass das Feld dann eine Eingabeprüfung auf "Numerische Zeichen" bekommt.
