### ISSUE TITLE
Falsches Datum bei wiederholenden Events im Reader

### ISSUE THREAD

**Issue by schaffen** [kmielke/calendar_extended#50]
Hallo Kester,

sorry, wenn ich Dich mit einem alten Thema sekkiere, aber ich komm leider auf keine Lösung.
Ich habe Contao 4.4.4 momentan im Einsatz und Deine calendar_extended 3.7.10. 
Wie schon des öfteren im Forum und hier auf github gelesen, sollte das Problem der falschen Datumsanzeige bei wiederholenden Events im Event Reader ja schon lange behoben sein. 

Ich hab mich auch durch die Einträge gewühlt und sicher den ganzen Nachmittag nach dem Fehler gesucht, ich komm aber einfach nicht dahinter. 

Ich wäre für ein paar hints sehr dankbar, da bei mir dieser Fehler auftaucht.

LG
Martin

**Comment by kmielke** [comment]
Hi Martin,

habe kurz reingeschaut. In der Tat werden URL's unter Contao 4 nicht so ausgegeben, wie in meinem Modul gebaut werden. Das muss ich mir ansehen. Unter 3.5 geht es noch.

Gruß Kester

**Comment by kmielke** [comment]
Fix ist in der kommenden Version enthalten
