### ISSUE TITLE
Doppelte Eingabefelder bei Anmeldung

### ISSUE THREAD

**Issue by planepix** [kmielke/calendar_extended#51]
Hallo Kester,

mit Contao 4.4.11 und der Dev-Master-Version erhalte ich beim Event und aktivierter Anmeldung zweimal die Felder für die Minimal- und Maximalanzahl der Teilnehmer (siehe Screenshot). 

Gäbe es noch ein Minus- oder Löschenicon wäre ich nicht irritiert; ich vermute mal das ist noch ein Bug?

Beste Grüße und guten Rutsch!
Thomas

![extended_calendar](https://user-images.githubusercontent.com/1823889/34455805-472b88e2-ed87-11e7-887c-b39b1f5a6101.png)

**Comment by kmielke** [comment]
Hallo Thomas,

ich mache den mal wieder zu, weil ich...

a) davon Ausgehe, dass du nicht calendar_extended, sondern calenar-extended-bundle meinst
und weil...
b) das bundle sowas von unbrauchbar ist, weil ich da nichts dran gemacht habe, ausser eine grobe Struktur zu schaffen. Das wird noch was dauern, bis das bundle in Version 1.0 kommt.

Sollte ich mich vertan haben, kannst du de gerne wieder aufmachen. Aber so oder so, wird da dieses Jahr nichts mehr dran passieren. ;)

Aber trotzdem danke für's Testen.

Ich wünsche einen guten Rutsch ins neue Jahr.
Gruß Kester
