### ISSUE TITLE
jquery-ui.min.css missing

### ISSUE THREAD

**Issue by janoschbatschi** [kmielke/calendar_extended#52]
PHP Fatal error: Uncaught exception 'Exception' with message 'File system/modules/calendar_extended/assets/fullcalendar/lib/jquery-ui.min.css does not exist' thrown in /system/modules/core/library/Contao/Combiner.php on line 134

**Comment by kmielke** [comment]
Die Datei fullcalendar/lib/jquery-ui.min.css ist im fullcalendar.zip nicht enthalten, und damit auch nicht in der Erweiterung.

**Comment by janoschbatschi** [comment]
OK, ist nachvollziehbar. Jedoch ist es frustrierend wenn man die Erweiterung installiert und verwenden will, einen Fehler bekommt und man dann erst auf die Suche gehen muss. Vllt. könnte man einen Link zu jQuery-UI bzw. die Problematik in der ReadMe erwähnen. 

Nichts desto trotz, vielen Dank für deine Arbeit!

**Comment by kmielke** [comment]
Ist komisch. Ich habe diesen Fehler noch nie gesehen. Du bist der Erste, der den meldet. Was ist bei deiner Nutzung so besonders?

**Comment by janoschbatschi** [comment]
Ansich nichts besonderes. In dem File "ModuleFullCalendar.php" ist in der Zeile 210 folgender Code
`$GLOBALS['TL_CSS'][] = $assets_path . '/fullcalendar/lib/cupertino/jquery-ui.min.css|static';
`
wo der Pfad ins leere führt und den Fehler verursacht.

**Comment by kmielke** [comment]
Dann lösch die Zeile. Ich werde das bei mir auch löschen. Wenn die Datei nicht da ist, sollte es auch nicht so sein.
