### ISSUE TITLE
Bei verkürzter Darstellung werden laufende Events nicht angezeigt

### ISSUE THREAD

**Issue by alexgit2k** [kmielke/calendar_extended#53]
Das in https://github.com/kmielke/calendar_extended/issues/35#issuecomment-271107115 beschriebene Problem ist noch offen: Laufende Events werden bei verkürzter Darstellung nicht angezeigt (keine Ausgabe), nur wenn "Verkürzte Darstellung" abgewählt wird.

**Comment by kmielke** [comment]
Ich brauche noch mehr Info's. was für Events sind das? Reden wir von Wiederholungen? Welche Version der Erweiterung? Welche Contao Version?

**Comment by alexgit2k** [comment]
Es handelt sich um keine Wiederholung, beim Event sind folgende Felder befüllt:
- Titel
- Event-Alias
- Autor
- Startdatum: 15.1.2018
- Enddatum: 21.01.2018
- Teasertext
- Weiterleitungsziel: Standard
- Event veröffentlichen: angehakt

Der Event läuft also die ganze Woche.

Beim Eventliste-Modul sind folgende Felder befüllt:
- Titel
- Überschrift
- Modultyp: Eventliste
- Kalender
- Verkürzte Darstellung: angehakt
- Anzeigeformat: Tag
- Sortierreihenfolge: aufsteigend
- Eventleser: -
- Anzahl an Events: 0
- Elemente pro Seite: 0
- Ferienkalender: Feiertage
- Event Template: event_teaser (global)
- Individuelles Template: -

Der Event wird an einem Tag in der laufenden Woche mit dieser Anstellung nicht angezeigt. Nur wenn "Verkürzte Darstellung" abgewählt wird, wird der Event angezeigt.

Systemumgebung:
- Contao Version 3.5.32 vom 18.1.2018 (https://github.com/contao/core/releases)
- calendar_extended 3.7.13 vom 21.12.2017 (https://github.com/kmielke/calendar_extended/releases)
- PHP 7.1.13

**Comment by kmielke** [comment]
Was hast du bei Kalender ausgewählt? Einen normalen Kalender?

**Comment by alexgit2k** [comment]
Ich habe das Problem: Ich hatte die Extension zuerst über das Contao Extension Repository installiert, die dort letzte Version 3.6.0. Da nach einer manuellen Aktualisierung der Extension auf 3.7 es dort noch immer 3.6.0 hieß, habe ich in Contao die Extension reparieren lassen, womit er dann wieder die 3.6.0 installiert hatte.

Mit 3.7.0 klappt es problemlos. Wie kann ich denn einstellen, dass in Contao die richtige Versionsnummer angezeigt wird und beim Reparieren nicht die alte Version installiert wird?

**Comment by kmielke** [comment]
Das kannst du so nicht einstellen, weil die aktuelle Version nicht über den ER installiert wurde. Wenn geht, dann installiere dir den Composer. Sonst schau im Contao Forum.

**Comment by alexgit2k** [comment]
Also ich denke am besten entfernt man dann den Extension-Eintrag in der Erweiterungsverwaltung, das habe ich folgendermaßen geschafft:

```
SELECT @id:=id FROM tl_repository_installs WHERE extension='calendar_extended';
DELETE FROM tl_repository_installs WHERE id=@id;
DELETE FROM tl_repository_instfiles WHERE pid=@id;
```
