### ISSUE TITLE
If Abfrage für Teilnehmer min/max

### ISSUE THREAD

**Issue by eBlick** [kmielke/calendar_extended#54]
<?php if ($this->reginfo): ?>
führt dazu, dass grundsätzlich die min/max Infos ausgegeben werden, da Default Werte = 0.

Ich habe mir nun mit 
<?php if ($this->reginfo['maxi'] > 0): ?>
beholfen, da nur bei Kursen mit Teilnehmerbegrenzung diese Infos ausgegeben werden sollen ( ich habe mehrere Kurse tw. mit tw. ohne Max)
Evtl. wäre hier eine andere If-Abfrage sinnvoll.

**Comment by kmielke** [comment]
möglicherweise wäre das sinnvoll. Allerdings ist es ein Beispiel, wie man es im Template lösen kann. Ich wollte kein fertiges Template liefern, da jeder sein eignes Ding hat. Template Angelegenheiten betrachte ich deswegen nicht als Fehler.
