### ISSUE TITLE
Div-Überlagerung bei Wiederholungen

### ISSUE THREAD

**Issue by eBlick** [kmielke/calendar_extended#55]
Die Felder
- Nur an Werktagen
- Intervall
- und Wiederholungen
lassen sich nicht anklicken, da eines der Divs überlagert.
Sie sind nur per Tab erreichbar.

**Comment by eBlick** [comment]
<img width="1066" alt="bildschirmfoto 2018-01-25 um 19 19 34" src="https://user-images.githubusercontent.com/6641281/35407906-969327e2-020d-11e8-9b9e-637f921deb63.png">

**Comment by kmielke** [comment]
welche contao version?

**Comment by eBlick** [comment]
4.4.12

**Comment by eBlick** [comment]
betrifft wohl das Wochentag widget "clr" statt "long" behebt es.

**Comment by kmielke** [comment]
fixed...

**Comment by kmielke** [comment]
Danke... ;)

**Comment by eBlick** [comment]
Wäre es möglich, dass mit dem Update etwas anderes krumm lief?
Ich habe gerade festgestellt, dass nach dem Update der eventtitle und eventid nicht mehr in Leads aufgelöst werden.

<img width="410" alt="bildschirmfoto 2018-01-26 um 18 52 17" src="https://user-images.githubusercontent.com/6641281/35453338-1ae60c6e-02ca-11e8-8792-175179a87679.png">

Damit ist auch der Bestätigungslink aus dem Notification Center ohne Funktion.
<img width="470" alt="bildschirmfoto 2018-01-26 um 18 53 43" src="https://user-images.githubusercontent.com/6641281/35453375-461c7bde-02ca-11e8-984f-33ea443f49fa.png">

**Comment by kmielke** [comment]
Hm... wüsste nicht wie. Hatte bzgl. des Themas nur long nach clt geändert, sonst nichts.

**Comment by eBlick** [comment]
sorry mein Fehler. NC Tokens waren fehlerhaft. Ist nicht ganz trivial der ganze Prozess....

Danke für die prima Erweiterung und fürs schnelle umsetzen.
