### ISSUE TITLE
Modulkonfiguration Eventliste: Nicht klickbare Felder durch fehlende CSS-Klasse

### ISSUE THREAD

**Issue by arno1979** [kmielke/calendar_extended#56]
Hallo Kester,

mir ist gestern aufgefallen, dass man in Contao 4 bei Konfiguration eines Moduls vom Typ "Eventliste" einige Felder in der Legend "Modul-Konfiguration (erweitert)" nicht anklicken bzw. ausfüllen kann.
Das betrifft die Felder: `show_holiday,ignore_urlparameter,cal_format_ext,displayDuration`.
Ausgelöst wird das durch eine fehlende CSS-Klasse auf dem Feld 'range_date'. Gibt man dem im 'eval'-Array ein `'tl_class' => 'clr'` mit, dann funktioniert es:
```php
// list of exceptions
$GLOBALS['TL_DCA']['tl_module']['fields']['range_date'] = array
(
    'label' => &$GLOBALS['TL_LANG']['tl_module']['range_date'],
    'exclude' => true,
    'inputType' => 'multiColumnWizard',
    'eval' => array
    (
        'columnsCallback' => array('calendar_Ext', 'getRange'),
        'buttons' => array('up' => false, 'down' => false, 'copy' => false),
        'tl_class' => 'clr'
    ),
    'sql' => "text NULL"
);
```
Unter Contao 3 machte das glaube ich keinen Unterschied, bin aber nicht 100% sicher.

Viele Grüße
Arno

**Comment by kmielke** [comment]
Hallo Arno,

danke, aber dir ist nicht aufgefallen, dass das in https://github.com/kmielke/calendar_extended/issues/55 schon gemeldet, und mit 3.7.15 bereits gefixt ist. ;)

Gruß Kester

**Comment by arno1979** [comment]
Das ist mir in der Tat nicht aufgefallen. :)
Was aber komisch ist: Ich bin laut Contao Manager auf der 3.7.15, aber der Fehler tritt bei mir trotzdem auf. Hmmm....

**Comment by kmielke** [comment]
Nein, du hast in der Tat recht. Mein Fehler... :(

**Comment by arno1979** [comment]
Alles gut. :)
Passt doch, wenn der Fehler behoben wird.

Danke dir!

**Comment by kmielke** [comment]
ist gefixt. Release mache ich jetzt.
Danke
