### ISSUE TITLE
Unregelmäßige Wiederholungen: Startzeit oder Endzeit 1:00 Uhr

### ISSUE THREAD

**Issue by arno1979** [kmielke/calendar_extended#57]
Hallo Kester,

mir ist aufgefallen, dass wenn man für einen unregemäßigen Wiederholungstermin die Uhrzeit "01:00" als Start- oder Endzeit eingibt, so wird das zwar beim ersten Speichern offensichtlich richtig in der Datenbank gespeichert:
```mysql
a:1:{i:0;a:4:{s:10:"new_repeat";s:10:"2018-04-10";s:9:"new_start";s:5:"01:00";s:7:"new_end";s:5:"02:00";s:6:"reason";s:0:"";}}
```

Im Backend-Feld wird dann aber einfach "0" ausgegeben.
Speichert man dann noch mal, wird dann logischerweise die "0" gespeichert:
```mysql
a:1:{i:0;a:4:{s:10:"new_repeat";s:10:"2018-04-10";s:9:"new_start";s:1:"0";s:7:"new_end";s:5:"02:00";s:6:"reason";s:0:"";}}
```
Speichert man dann nochmal erscheint im Backend-Feld absurderweise wieder korrekt die "01:00" .
So geht das immer hin- und her, hat aber natürlich zur Folge, dass im Frontend gelegentlich die falsche Uhrzeit für den Termin ausgegeben wird.

Das Phänomen tritt übrigens ausschließlich mit der Uhrzeit "01:00" auf. Andere Werte die ich getestet habe: "02:00", "00:55", "01:01" werden immer wie eingegeben gespeichert und auch wieder im Feld ausgegeben.

Ich vermute, dass es irgendwas mit dem "adjustTime" Callback zu tun hat, habe das aber nicht genauer nachvollziehen können.

Viele Grüße
Arno

**Comment by kmielke** [comment]
hm... sehr sehr komisch. Aktuell würde ich sagen, dass das ein Bug im MultiColumnWizard ist. Warum auch immer, wird das Feld durch den columnsCallback falsch belegt.
```
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['repeatFixedDates'] = array
 (
    'label' => &$GLOBALS['TL_LANG']['tl_calendar_events']['repeatFixedDates'],
    'exclude' => true,
    'inputType' => 'multiColumnWizard',
    'eval' => array
    (
        'columnsCallback' => array('tl_calendar_events_ext', 'listFixedDates'),
        'buttons' => array('up' => false, 'down' => false)
    ),
    'sql' => "blob NULL"
 );
```
Gruß Kester

**Comment by arno1979** [comment]
Verstehe... so weit war ich gar nicht gekommen. :)
Sollte man das dann bei https://github.com/menatwork/MultiColumnWizard als Ticket anlegen, oder?
Ich? Du?

Viele Grüße
Arno

**Comment by kmielke** [comment]
Wenn du das heuten machen möchtest, gerne. 👍  
Danke dir.

Gruß Kester

**Comment by arno1979** [comment]
Ist gemacht:
https://github.com/menatwork/MultiColumnWizard/issues/252

**Comment by kmielke** [comment]
Hallo Arno,
ich mache den mal zu hier, da es ja ein Bug im MultiColumnWizard ist. Ich danke dir für dein Feedback. ;)
Gruß Kester
