### ISSUE TITLE
No events in list after update

### ISSUE THREAD

**Issue by Aybee** [kmielke/calendar_extended#60]
Ich habe gerade in Contao 3.5.35 die Version 3.6.0 manuell auf Version 3.7.18 upgedatet. Danach zeigen die Listen im FE keine Events mehr an. Gibt es dabei irgendetwas zu beachten, was mir entgangen ist?

**Comment by kmielke** [comment]
Keine Ahnung. Die Version 3.6 wird schon seit langem nicht mehr unterstützt, und ich habe NIE ein update von dieser Version auf die aktuelle gemacht. Gründe kann es jetzt hunderte geben. Allerdings ist deine Beschreibung sehr schlicht.

Da es keine "echte" Fehlerbeschreibung gibt, mache ich den hier wieder zu.

Bitte versuche es erstmal über das Forum: https://community.contao.org/de/forumdisplay.php?160-calendar_extended

Beschreibe möglichst genau, was du wie gemacht hast, und was für Meldungen (Error, Warnings...) bekommen hast, usw... Auch wäre wichtig, was die Logs sagen.

Gruß Kester

**Comment by Aybee** [comment]
Forum: https://community.contao.org/de/showthread.php?71071-Nach-Update-von-3-6-0-auf-3-7-18-keine-Anzeige-von-Events-in-den-Listen&p=475519#post475519
