### ISSUE TITLE
repeatDates wird bei "normalen" Wiederholungen falsch ermittelt

### ISSUE THREAD

**Issue by wiphi** [kmielke/calendar_extended#62]
Problem: Das interne Feld `repeatDates` wird beim Speichern eines Events mit normalen Wiederholungen falsch berechnet.

Reproduzierbar: 
Neues Event mit folgenden Daten anlegen
- Startdatum 04.02.2019, Startzeit 19:30 Uhr
- Wiederholung Intervall: 1 Tag
- Anzahl Wiederholungen: 3

Zu erwarten wäre, dass das Feld repeatDates folgende Datumswerte ermittelt:
04.02., 05.02., 06.02., 07.02.

gespeichert werden jedoch nur
04.02., 05.02., 06.02.

Das Ende der Wiederholungen wird aber korrekt auf den 07.02. gesetzt.

Lösungsvorschlag:
Schuld an dem fehlenden letzten Datum ist die Zeile:
https://github.com/kmielke/calendar_extended/blob/23b266f2ee0dc2002610ec103f1a2daa7a19f247/dca/tl_calendar_events.php#L725-L727

meines Erachtens nach müsste sie so ` if ($next > $end` lauten. Wenn ich diese so bei mir ändere, kommen die Datumswerte wie gewünscht in dem Feld an.

**Comment by wiphi** [comment]
Weil das Datum der letzten Wiederholung doch genauso in diesem Feld mit enthalten sein sollte, wie alle anderen.
<img width="450" alt="calendar_extended_repeatdates" src="https://user-images.githubusercontent.com/25878910/50740719-f6177100-11f2-11e9-8e42-2542ba3f2c07.png">

**Comment by kmielke** [comment]
Ich hatte dich schon verstanden, aber warum? Wo ist das Problem?

**Comment by kmielke** [comment]
Conrad Version? Version der Erweiterung?

**Comment by wiphi** [comment]
Ich verwende das Feld für eine Auswertung in einem Contao-Modul.
Mein Setup ist
Contao: 3.5.38
calendar_extended: 3.7.18

**Comment by kmielke** [comment]
Ok, verstehe. Das Feld ist, zumindest für mich, nur für interne Zwecke gedacht. Die Version 3 für Contao 3.x bekommt nur noch wichtige Bugfixes, wozu ich den jetzt nicht zähle. Sorry...
Gruß Kester

**Comment by wiphi** [comment]
Ok, trotzdem Danke für die Info.
Wie sieht das für die Bundle Version der 4 aus?
